### ISSUE TITLE
There should be an easy way to reference the LOD predicate for things mentioned

### ISSUE THREAD

**Issue by workergnome** [azaroth42/museum-lod#10]
Often, I want to look at with URL is used for a given property.  I agree with having the default view be the JSON key, but there should be an easy way for an informed user to look up what that key represents in the provided context.

**Comment by azaroth42** [comment]
Could have a global replace for \`key_name\` to &lt;code>&lt;abbr expan="crm:predicate>key_name&lt;/abbr>&lt;/code> or similar? That would make it easy for when they're refered to in the text.  Linking from the examples seems like just having a turtle representation at the bottom with raw and playground would be just as good there.

**Comment by azaroth42** [comment]
Done using <abbr> for the moment. If there's a better way to control the rendering, let me know!

**Comment by workergnome** [comment]
Works for now.  There might be a way to use something like https://popper.js.org to style it, but it's good enough to be useful as is.

**Comment by azaroth42** [comment]
Closing, and will open a new issue to improve the styling
