### ISSUE TITLE
Simplify technique key in context?

### ISSUE THREAD

**Issue by azaroth42** [azaroth42/museum-lod#13]
Proposed: `used_general_technique` --> `technique`

P33 used_specific_technique is for following explicitly referenced procedure documents (with their own class E29, subclass of E73 Information Object) and (thus) very unlikely to ever be used.

Resulting in:

```
{
  "type": "Production",
  "carried_out_by": {"label": "Dale Chihuly"},
  "technique": "http://vocab.gett.edu/aat/300053932" // glassblowing
}
```

**Comment by workergnome** [comment]
I'm a fan of `technique` and `specific_technique`.

**Comment by azaroth42** [comment]
Done technique. Need to do specific_technique.

**Comment by azaroth42** [comment]
Done and live.
