### ISSUE TITLE
exhibition venue aat term?

### ISSUE THREAD

**Issue by azaroth42** [azaroth42/museum-lod#15]
Is it just an exhibition? Or for traveling exhibitions, should the top event be explicitly http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300054773 
and then each exhibition-at-venue an exhibition?

But then we're inconsistent between exhibition and venue for exhibitions that only have a single venue.

Propose to have exhibitions consist_of exhibitions unless I hear from Patricia otherwise that there's a good term for a venue?

**Comment by workergnome** [comment]
Each exhibition at a venue is an exhibition, in my opinion.  

I'm also OK with the master exhibition being also an `exhibition`([aat:300054766](http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300054766)), since that's the superclass of the other types.  Assuming inheritance, I think that's fine—it might be _more_ true to have `traveling_exhibition` consist_of `exhibitions`, but that's just nuance.

**Comment by azaroth42** [comment]
Okay, exhibition consists_of exhibition it is! :)

**Comment by azaroth42** [comment]
Thinking further about this ... splitting overall exhibition from events-with-time-and-place-for-exhibition is necessary for traveling exhibitions, but if there's just a single location and set of dates, then the description of the two separately (overall exhibition, single location) seems very redundant.

In favor:  
  * consistency -- there's always a super-exhibition, even if there's only one venue.

Against: 
  * redundancy -- the two exhibitions will have exactly the same information. 

We don't always require the same number of "levels" for other partitioning cases, because reality doesn't work like that and because we likely don't have the same information across different use cases.   Explaining the inconsistency with the larger model, and thus the comprehension cost, seems to outweigh the consistency gain with always having a super-exhibition.

So I'd like to at least re-discuss the following:

* If the exhibition has a single venue, then there's just an E7 with aat:exhibition.
* If the exhibition has multiple venues, each is an E7 with aat:exhibition for each stop, and an E7 with aat:travelling_exhibition that consists_of each of the stops.

**Comment by workergnome** [comment]
Ah—I had assumed the levels as you have just stated them. I thought we were only talking about multi-stop exhibitions, and you were pushing for not having two different AAT terms for exhibition at the top level.  I'm even more in favor of these modifications.

**Comment by azaroth42** [comment]
Oh, good :) Glad that we were on the same page, inadvertently!

**Comment by azaroth42** [comment]
Closing again :)
