### ISSUE TITLE
Should  @type be mapped to type @vocab in context?

### ISSUE THREAD

**Issue by workergnome** [azaroth42/museum-lod#17]
https://github.com/azaroth42/museum-lod/blob/master/content/ns/context/1/full.jsonld#L21

This has changed, and now my various types are no longer being mapped to `"type": "ManMadeObject"`:  they're now back to `"@type": "ManMadeObject"` when I frame using this context.

**Comment by azaroth42** [comment]
Huh.  If you frame with "@type": "@type" instead of "@type": "@vocab" does that work?

**Comment by workergnome** [comment]
```
    "type": {
      "@id": "@type", 
      "@type": "@id"
    }, 
```

works.

```
    "type": {
      "@id": "@type", 
      "@type": "@type"
    }, 
```

You can play with this file if you'd like.
[002_lc_s6.txt](https://github.com/azaroth42/museum-lod/files/843118/002_lc_s6.txt)


crashes the JSON-LD Playground.

**Comment by azaroth42** [comment]
I believe that's a bug in framing, or I completely misunderstand the difference between `@type:@id` and `@type:@vocab`.

From the [spec](https://www.w3.org/TR/json-ld/#type-coercion):
> Alternatively, the keywords `@id` or `@vocab` may be used as value to indicate that within the body of a JSON-LD document, a string value of a term coerced to `@id` or `@vocab` is to be interpreted as an IRI. The difference between `@id` and `@vocab` is how values are expanded to absolute IRIs. `@vocab` first tries to expand the value by interpreting it as term. If no matching term is found in the active context, it tries to expand it as compact IRI or absolute IRI if there's a colon in the value; otherwise, it will expand the value using the active context's vocabulary mapping, if present, or by interpreting it as relative IRI. Values coerced to `@id` in contrast are expanded as compact IRI or absolute IRI if a colon is present; __otherwise, they are interpreted as relative IRI__. 

[emph added]

I believe that if it's not @type:@vocab, then "type": "ManMadeObject" would be interpreted as a relative URI, from the base id.  e.g. if the base id was `http://example.org/stuff/', then it would expand not to the CRM term, but to `http://example.org/stuff/ManMadeObject`.

Thoughts?

**Comment by workergnome** [comment]
Interesting.  Yeah, it looks like it might be a bug in framing.  I agree the spec seems to agree with you, and it certainly does the right thing in expansion.  Time to send up a bat-symbol?

**Comment by azaroth42** [comment]
:bat: symbol got timely response from @gkellogg that we've messed it up here, IIIF, and Annotations. Doh. Corrected here: https://linked.art/ns/context/1/full.jsonld and issue/erratum raised on the other two.
