### ISSUE TITLE
Should Materials in AAT use prefix: form?

### ISSUE THREAD

**Issue by azaroth42** [azaroth42/museum-lod#2]
like p2 does?

**Comment by azaroth42** [comment]
If they're the `@id` of a resource, then they have to follow the requirements of the keyword...

> If the node object contains the @id key, its value must be an absolute IRI, a relative IRI, or a compact IRI (including blank node identifiers). 

So they could be aat:30001000 but not aat_conceptname, as that would be a term in the context, not a compact IRI.

**Comment by azaroth42** [comment]
To be clear `{"made_of" : "aat_watercolor"}` is okay, but `{"id": "aat_watercolor"}` is not.

Meaning that if you were to add a label to the concept, the serialization would have to shift from:

```
{
  "made_of": "aat_watercolor"
}
```

to 

```
{
  "made_of": {
    "id": "aat:3000010000",
    "label": "watercolor"
  }
}
```

Which is not ideal and a real use case. It would then be weird to do it for p2, even though there's much less need to have a label.

**Comment by azaroth42** [comment]
Propose close won't fix -- We should establish the convention that `id` is always a full URI.
@workergnome?

With agreement, I'll close and make an issue to document that.

**Comment by workergnome** [comment]
Concur. Full URI, or aat:12345 form, but not a non-curried Term. .

**Comment by azaroth42** [comment]
Full URI or CURIE for `id`? My preference is always a full URI for consistency, unless there's a particular reason for CURIEs? The consistency makes it easier to merge the graph in a non RDF context, rather than having to expand all the prefix forms first.

**Comment by workergnome** [comment]
Maybe this is a terminology issue.  Are you proposing

```
{
  "made_of": {
    "id": "aat: 300015045",
    "label": "watercolor"
  }
```

or 

```
{
  "made_of": {
    "id": "http://vocab.getty.edu/aat/300015045",
    "label": "watercolor"
  }

**Comment by azaroth42** [comment]
I'm proposing that the latter be the only way to represent URIs in the `id` property.  Otherwise some `id`s will look like URIs, some won't.  We can discuss blank nodes separately :)

So fully formed URI = 👍 , but prefix:slug = :-1: and all forms of relative URI = :-1:

**Comment by azaroth42** [comment]
Nope, as @workergnome points out, JSON-LD compaction will always result in the most compact form.  So by defining `aat` in the context, we ensure that ids will be of the form `aat:123456` not the full URI.

From https://www.w3.org/TR/json-ld-api/#compaction-algorithm:
> This algorithm compacts a JSON-LD document, such that the given context is applied. This must result in shortening any applicable IRIs to terms or compact IRIs, any applicable keywords to keyword aliases, and any applicable JSON-LD values expressed in expanded form to simple values such as strings or numbers.

As `id` can't be a fully context-dependent term, and we can't prevent either URIs or prefix:form CURIEs, propose close wontfix and document it.
