### ISSUE TITLE
There should be  an easy way to link to subsections

### ISSUE THREAD

**Issue by workergnome** [azaroth42/museum-lod#8]
When writing issues, it would be really helpful to have some sort of "link" icon to allow me to easily copy/paste to headers within the document, much like Github.  The anchor tags exist, but there's no easy way to access them.

**Comment by azaroth42** [comment]
Agree. I started this a while ago (try putting mouse just left of a sub-heading) but the chain link trick from IIIF specs seems to rely on some magic that I don't understand.

**Comment by workergnome** [comment]
It's probably a CSS :before section:  https://www.w3schools.com/cssref/sel_before.asp

**Comment by workergnome** [comment]
(actually, it's an :after CSS statement:

```css
[data-anchorjs-icon]::after {
    content: attr(data-anchorjs-icon);
}
```
